---
- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state : restarted
    enabled: yes  

- name: restart mariadb-server
  service: 
    name: mariadb-server
    state: restarted
    enabled: yes
