- name: apt update
  tags: apt_update
  apt:
    update-cache: yes
    cache_valid_time: 3600

- name: Installation d'Apache
  tags: apache2
  apt:
    name: apache2
    state: latest

- name: Installation de Nagios4
  tags: nagios4
  apt:
    name: nagios4
    state: latest

- name: Copie du fichier nagios4-cgi.conf pour la ligne "Require Valid User"
  tags: nagios4-cgi.conf
  template:
    src: nagios4-cgi.conf.j2
    dest: /etc/apache2/conf-enabled/nagios4-cgi.conf
  notify: restart nagios4

- name: On exécute la commande pour le cgi
  tags: cgi
  command: a2enmod rewrite cgi

- name: On redémarre apache2
  tags: reload
  service:
    name: apache2
    state: restarted
    enabled: yes
